name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Lint
        run: terraform fmt -check -recursive

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
            tflint_version: v0.52.0
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
            # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
            GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

      - name: Create Release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
